"""
app.py
------
FastAPI application entry point for the ORKA Equipment Knowledge Library.

Exposes a REST API with four endpoints for managing ValidationEntry records
(lessons learned from pharmaceutical equipment validation projects).
The frontend (index.html) is served from the /static directory and consumes
these endpoints directly.

To run the server locally:
    uvicorn main.app:app --reload

API docs are auto-generated by FastAPI and available at:
    http://localhost:8000/docs
"""

import os
import logging
from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.staticfiles import StaticFiles
from typing import List
from uuid import UUID
from main.models import ValidationEntry
from main.models import ChatRequest, ChatResponse, ChatSources
from main.local_db import test_db
from main.vector_embed import VectorEmbedder
from main.vector_embed import embed_text
from main.ingest_document import ingest_document, SUPPORTED_TYPES
from fastapi.responses import FileResponse
from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

app = FastAPI(title="ORKA Equipment Knowledge Library")


@app.get("/")
async def root():
    """Serve the landing page."""
    return FileResponse("main/public/landing.html")


@app.get("/library")
async def library_page():
    """Serve the equipment library dashboard."""
    return FileResponse("main/public/index.html")


@app.get("/assistant")
async def chat_page():
    """Serve the AI chat and document upload page."""
    return FileResponse("main/public/chat.html")


@app.get("/chat")
async def chat_page_alias():
    """Serve the AI chat page at the documented /chat route."""
    return FileResponse("main/public/chat.html")


@app.get("/entries", response_model=List[ValidationEntry], tags=["Entries"])
async def get_entries():
    """
    Retrieve all validation lesson learned entries from the database.

    Returns a list of ValidationEntry objects. Returns an empty list if
    no entries have been logged yet.
    """
    try:
        return test_db.get_entries()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/entries", response_model=ValidationEntry, tags=["Entries"])
async def create_entry(entry: ValidationEntry):
    """
    Log a new equipment validation lesson learned.

    Accepts a ValidationEntry JSON body. The 'id' field is auto-generated
    if not provided. Returns the saved entry on success.
    """
    try:
        saved = test_db.create_entry(entry)
        try:
            embedding = VectorEmbedder(entry).embed()
            test_db.update_embedding(str(entry.id), embedding)
        except Exception as embed_err:
            logger.warning("Embedding failed for entry %s: %s", entry.id, embed_err)
        return saved
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.put("/entries/{entry_id}", response_model=ValidationEntry, tags=["Entries"])
async def update_entry(entry_id: str, entry: ValidationEntry):
    """Update an existing validation lesson."""
    try:
        updated = test_db.update_entry(entry_id, entry)
        try:
            embedding = VectorEmbedder(entry).embed()
            test_db.update_embedding(entry_id, embedding)
        except Exception as embed_err:
            logger.warning("Embedding update failed for entry %s: %s", entry_id, embed_err)
        return updated.copy(update={"id": UUID(entry_id)})
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat", response_model=ChatResponse, tags=["Chat"])
async def chat(request: ChatRequest):
    """
    Handle chat requests and generate AI responses.
    Stage 1: embed the question
    Stage 2: search DB
    Stage 3: build prompt
    Stage 4: call LLM
    """
    try:
        # Stage 1
        queryvector = embed_text(request.query)

        # Stage 2 - search Tier 1 (lessons learned) and Tier 2 (uploaded manuals)
        entry_results = test_db.search_entries(queryvector)
        doc_results = test_db.search_documents(queryvector)

        # Stage 3 - build context and sources from both tiers
        context = ''
        sources = []

        for row in entry_results:
            context += f"\n[ORKA Entry: {row['equipment_system']} | {row['validation_phase']}]\nID: {row['id']}\nObstacle: {row['obstacle']}\nResolution: {row['resolution']}\n---"
            sources.append(ChatSources(
                source_id=str(row["id"]),
                equipment_system=row["equipment_system"],
                phase=row["validation_phase"],
                source_type="entry"
            ))

        seen_docs = set()
        for row in doc_results:
            context += f"\n[Manual: {row['filename']}, chunk {row['chunk_index']}]\nEquipment Tag: {row['equipment_tag']}\nContent: {row['content_chunk']}\n---"
            if row["filename"] not in seen_docs:
                seen_docs.add(row["filename"])
                sources.append(ChatSources(
                    source_id=str(row["id"]),
                    equipment_system=row["equipment_tag"] or row["filename"],
                    phase="N/A",
                    source_type="document"
                ))
        
        system_prompt = """You are an internal assistant for ORKA Consulting Partners.
        Answer ONLY using the context entries provided. For every fact you state, cite the Entry ID it came from.
        If the context does not contain relevant information, respond using EXACTLY this format:

        No relevant entries exist from ORKA knowledge base. [no relevant entries]

        I will proceed to answer from my own AI general knowledge:

        [your answer here]

        Do not deviate from this format when falling back to general knowledge."""

        full_prompt = f"{system_prompt}\n\nContext Entries:\n{context}\n\nUser Query: {request.query}"

        # Stage 4
        _client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
        response = _client.models.generate_content(model='gemini-2.5-flash',contents=full_prompt)

        return ChatResponse(answer=response.text, sources=sources)

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))



@app.post("/documents/upload", tags=["Documents"])
async def upload_document(
    file: UploadFile = File(...),
    equipment_tag: str = Form(...),
    uploaded_by: str = Form(...),
):
    """
    Upload a PDF equipment manual or troubleshooting guide.
    Extracts text, chunks it, generates embeddings, and stores all chunks
    in the documents table for retrieval by the /chat endpoint.
    """
    ext = "." + file.filename.lower().rsplit(".", 1)[-1]
    if ext not in SUPPORTED_TYPES:
        raise HTTPException(status_code=400, detail=f"Unsupported file type. Accepted: {', '.join(SUPPORTED_TYPES)}")

    try:
        file_bytes = await file.read()
        result = ingest_document(
            filename=file.filename,
            file_bytes=file_bytes,
            equipment_tag=equipment_tag,
            uploaded_by=uploaded_by,
        )
        if result["status"] == "skipped":
            raise HTTPException(status_code=422, detail=result["reason"])
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/entries/{entry_id}", tags=["Entries"])
async def delete_entry(entry_id: str):
    """
    Permanently delete a validation entry by its UUID.

    Returns a confirmation message on success.
    """
    try:
        test_db.delete_entry(entry_id)
        return {"message": "Entry deleted successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# Mount the frontend static files directory if it exists.
# This serves JS, CSS, and other assets at /static/...
if os.path.exists("main/public"):
    app.mount("/static", StaticFiles(directory="main/public"), name="static")
