"""
app.py
------
FastAPI application entry point for the ORKA Equipment Knowledge Library.

Exposes a REST API with four endpoints for managing ValidationEntry records
(lessons learned from pharmaceutical equipment validation projects).
The frontend (index.html) is served from the /static directory and consumes
these endpoints directly.

To run the server locally:
    uvicorn main.app:app --reload

API docs are auto-generated by FastAPI and available at:
    http://localhost:8000/docs
"""

import os
import logging
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from typing import List
from main.models import ValidationEntry
from main.local_db import test_db
from main.vector_embed import VectorEmbedder

from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)

app = FastAPI(title="ORKA Equipment Knowledge Library")


@app.get("/")
async def root():
    """Serve the main frontend dashboard (index.html)."""
    return FileResponse("main/public/index.html")


@app.get("/entries", response_model=List[ValidationEntry], tags=["Entries"])
async def get_entries():
    """
    Retrieve all validation lesson learned entries from the database.

    Returns a list of ValidationEntry objects. Returns an empty list if
    no entries have been logged yet.
    """
    try:
        return test_db.get_entries()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/entries", response_model=ValidationEntry, tags=["Entries"])
async def create_entry(entry: ValidationEntry):
    """
    Log a new equipment validation lesson learned.

    Accepts a ValidationEntry JSON body. The 'id' field is auto-generated
    if not provided. Returns the saved entry on success.
    """
    try:
        saved = test_db.create_entry(entry)
        try:
            embedding = VectorEmbedder(entry).embed()
            test_db.update_embedding(str(entry.id), embedding)
        except Exception as embed_err:
            logger.warning("Embedding failed for entry %s: %s", entry.id, embed_err)
        return saved
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.put("/entries/{entry_id}", response_model=ValidationEntry, tags=["Entries"])
async def update_entry(entry_id: str, entry: ValidationEntry):
    """
    Update (fully replace) an existing validation entry by ID.

    All fields in the request body overwrite the existing record.
    Partial updates (PATCH) are not currently supported.
    """
    try:
        return test_db.update_entry(entry_id, entry)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/entries/{entry_id}", tags=["Entries"])
async def delete_entry(entry_id: str):
    """
    Permanently delete a validation entry by its UUID.

    Returns a confirmation message on success.
    """
    try:
        test_db.delete_entry(entry_id)
        return {"message": "Entry deleted successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# Mount the frontend static files directory if it exists.
# This serves JS, CSS, and other assets at /static/...
if os.path.exists("main/public"):
    app.mount("/static", StaticFiles(directory="main/public"), name="static")
